[project]
name = "task-manager-clean"
version = "0.1.0"
description = "Planning de tâches basé sur un graphe de dépendances (tri topologique, livraisons, Gantt)"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Ludovic Courtin", email = "ludovic.courtin@etu.univ-tours.fr" } {}]
dependencies = [
  "networkx",
  "rich"
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.mypy]
python_version = "3.13"
strict = true
files = ["src"]

